HIDE_CURSOR_CODE = "\033[?25l"
SHOW_CURSOR_CODE = "\033[?25h"
MAX_MATRIX_STRING_SIZE = 12
MIN_MATRIX_STRING_SIZE = 6
MATRIX_STRING_GENERATOR_INTERVAL = 0.1
MATRIX_RENDERER_RATE = 0.04
POSSIBLE_MATRIX_STRING_CHARACTERS = "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ"
